export const selectOptions = [
  { value: 'FATHER', label: 'Father' },
  { value: 'MOTHER', label: 'Mother' },
  { value: 'BROTHER', label: 'Brother' },
  { value: 'SISTER', label: 'Sister' },
  { value: 'GRANDFATHER', label: 'Grandfather' },
  { value: 'GRANDMOTHER', label: 'GrandMother' },
  { value: 'GRANDSON', label: 'Grandson' },
  { value: 'GRANDDAUGHTER', label: 'Granddaughter' },
  { value: 'AUNT', label: 'Aunt' },
  { value: 'UNCLE', label: 'Uncle' },
  { value: 'COUSIN', label: 'Cousin' },
  { value: 'NEPHEW', label: 'Nephew' },
  { value: 'NIECE', label: 'Niece' },
];
